# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: quickfix-jruby 1.6.0 java lib

Gem::Specification.new do |s|
  s.name = "quickfix-jruby"
  s.version = "1.6.0"
  s.platform = "java"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chris Busbey"]
  s.date = "2017-09-08"
  s.description = "QuickFIX/J packaged as a gem for JRuby"
  s.email = "support@connamara.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "CONTRIBUTION_GUIDELINES.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "QUICKFIX_LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/dom4j-1.6.1.jar",
    "lib/jaxen-1.1.4.jar",
    "lib/jcl-over-slf4j-1.7.12.jar",
    "lib/je-2.1.30.jar",
    "lib/mina-core-2.0.9.jar",
    "lib/proxool-0.9.1.jar",
    "lib/quickfix.rb",
    "lib/quickfixj-core-1.6.4.jar",
    "lib/quickfixj-messages-fix40-1.6.4.jar",
    "lib/quickfixj-messages-fix41-1.6.4.jar",
    "lib/quickfixj-messages-fix42-1.6.4.jar",
    "lib/quickfixj-messages-fix43-1.6.4.jar",
    "lib/quickfixj-messages-fix44-1.6.4.jar",
    "lib/quickfixj-messages-fix50-1.6.4.jar",
    "lib/quickfixj-messages-fix50sp1-1.6.4.jar",
    "lib/quickfixj-messages-fix50sp2-1.6.4.jar",
    "lib/quickfixj-messages-fixt11-1.6.4.jar",
    "lib/slf4j-api-1.7.12.jar",
    "lib/slf4j-jdk14-1.7.12.jar",
    "quickfix-jruby.gemspec",
    "test/helper.rb",
    "test/tc_quickfix.rb"
  ]
  s.homepage = "http://github.com/connamara/quickfix-jruby"
  s.licenses = ["GPL"]
  s.rubygems_version = "2.4.8"
  s.summary = "Gemified QuickFIX/J"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_development_dependency(%q<rake>, ["~> 10.1"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
      s.add_dependency(%q<rake>, ["~> 10.1"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
    s.add_dependency(%q<rake>, ["~> 10.1"])
  end
end

